@BASE_URL = http://localhost:3000

GET {{BASE_URL}}

###
GET {{BASE_URL}}/api/user

###
POST {{BASE_URL}}/api/user
Content-Type: application/json

{
    "name" : "haso",
    "username" : "cry",
    "email" : "hasantunahan12345@gmail.com",
    "password" :"pes"
}

###
DELETE {{BASE_URL}}/api/user/6083f99a5e0b04125035d5

###
PATCH {{BASE_URL}}/api/user/6083f9dc5e0b04125035d534
Content-Type: application/json

{
    "password"  :"awfawf"
}


###
POST {{BASE_URL}}/api/user/login
Content-Type: application/json

{
    "email" : "hasantunahan12345@gmail.com",
    "password" :"pes"
}